/**
 * Stand-in for the third-party STT vendor's own worker, for local dev/testing only.
 * Run with `npm run mock:stt-worker`.
 *
 * Consumes `transcript-generation` jobs (exactly the contract the real vendor would
 * receive — see `src/core/queue/payloads.ts`), waits briefly to simulate transcription
 * latency, then produces a canned `transcript-ready` job back onto the same Redis so
 * our own `TranscriptReadyProcessor` can be exercised end-to-end without a real vendor
 * wired in yet (per the plan's build order, step 4).
 *
 * Never import this file from `src/app.module.ts` or anything the real app boots —
 * it deliberately lives outside the Nest DI graph, exactly like a real external vendor
 * would be a wholly separate process.
 */
import { Queue, Worker } from 'bullmq';
import { loadEnv, getEnv, getEnvNumber } from '@config/env';
import type {
  TranscriptGenerationJobPayload,
  TranscriptReadyJobPayload,
} from '@core/queue/payloads';
import { QUEUE_NAMES } from '@core/queue/queue.constants';

loadEnv();

const connection = {
  host: getEnv('REDIS_HOST', 'localhost'),
  port: getEnvNumber('REDIS_PORT', 6379),
  password: getEnv('REDIS_PASSWORD', '') || undefined,
  maxRetriesPerRequest: null,
};

const readyQueue = new Queue<TranscriptReadyJobPayload>(QUEUE_NAMES.TRANSCRIPT_READY, {
  connection,
});

function fakeTranscriptFor(questionText: string): string {
  return `[mock transcript] Candidate's answer to: "${questionText}". This is a simulated response generated by the local STT vendor stub for development/testing.`;
}

const worker = new Worker<TranscriptGenerationJobPayload>(
  QUEUE_NAMES.TRANSCRIPT_GENERATION,
  async (job) => {
    const { interviewId, candidateId, organizationId, questions } = job.data;
    console.log(
      `[mock-stt-worker] received transcript-generation for interview ${interviewId} (${questions.length} question(s))`,
    );

    // Simulate real transcription latency.
    await new Promise((resolve) => setTimeout(resolve, 2_000));

    const payload: TranscriptReadyJobPayload = {
      interviewId,
      candidateId,
      organizationId,
      status: 'SUCCESS',
      transcript: {
        combinedText: questions.map((q) => fakeTranscriptFor(q.questionText)).join('\n\n'),
        perQuestion: questions.map((q) => ({
          questionId: q.questionId,
          transcriptText: fakeTranscriptFor(q.questionText),
        })),
        language: 'en',
      },
      processedAt: new Date().toISOString(),
      aiServiceJobId: `mock-${job.id}`,
    };

    await readyQueue.add('transcript-ready', payload, {
      jobId: interviewId,
      removeOnComplete: true,
      removeOnFail: false,
    });
    console.log(`[mock-stt-worker] produced transcript-ready for interview ${interviewId}`);
  },
  { connection },
);

worker.on('failed', (job, err) => {
  console.error(`[mock-stt-worker] job ${job?.id} failed:`, err);
});

console.log(
  `[mock-stt-worker] listening on "${QUEUE_NAMES.TRANSCRIPT_GENERATION}", will produce onto "${QUEUE_NAMES.TRANSCRIPT_READY}" — Ctrl+C to stop`,
);

async function shutdown(): Promise<void> {
  console.log('[mock-stt-worker] shutting down...');
  await worker.close();
  await readyQueue.close();
  process.exit(0);
}
process.on('SIGINT', () => void shutdown());
process.on('SIGTERM', () => void shutdown());
