import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { LlmService } from '@core/llm';
import { Candidate } from '@module/candidates/entities';
import { Interview } from '@module/interviews/entities';
import { MailAccountsService } from '@module/mail-accounts';
import { EmailTone, OrganizationSettings } from '@module/organizations/entities';
import { CandidateEmail } from './entities';
import { ComposeEmailDto, SendEmailDto } from './dto';

export interface ComposedEmail {
  subject: string;
  body: string;
}

const TONE_DESCRIPTIONS: Record<EmailTone, string> = {
  [EmailTone.PROFESSIONAL]: 'warm, concise, and professional',
  [EmailTone.FRIENDLY]: 'friendly and conversational, while staying respectful',
  [EmailTone.CONCISE]: 'brief and to-the-point — no more than a couple of short sentences',
  [EmailTone.WARM]: 'warm, personable, and encouraging',
};

/**
 * The second of the three real, backend-owned LLM call sites (question generation and
 * evaluation are the other two). `compose` is a pure LLM call — nothing is persisted
 * or sent until the recruiter reviews the draft and calls `send`.
 */
@Injectable()
export class EmailComposerService {
  constructor(
    @InjectRepository(Candidate)
    private readonly candidatesRepository: Repository<Candidate>,
    @InjectRepository(Interview)
    private readonly interviewsRepository: Repository<Interview>,
    @InjectRepository(CandidateEmail)
    private readonly emailsRepository: Repository<CandidateEmail>,
    @InjectRepository(OrganizationSettings)
    private readonly orgSettingsRepository: Repository<OrganizationSettings>,
    private readonly llmService: LlmService,
    private readonly mailAccountsService: MailAccountsService,
  ) {}

  private async loadCandidate(organizationId: string, candidateId: string): Promise<Candidate> {
    const candidate = await this.candidatesRepository.findOne({
      where: { id: candidateId, organizationId },
      relations: { job: true },
    });
    if (!candidate) throw new NotFoundException('Candidate not found');
    return candidate;
  }

  async compose(
    organizationId: string,
    candidateId: string,
    dto: ComposeEmailDto,
  ): Promise<ComposedEmail> {
    const settings = await this.orgSettingsRepository.findOne({ where: { organizationId } });
    if (settings && !settings.aiEmailDraftingEnabled) {
      throw new BadRequestException(
        'AI email drafting is turned off for your organization. An admin can re-enable it in Settings → AI settings, or write this email manually.',
      );
    }
    const tone = TONE_DESCRIPTIONS[settings?.emailTone ?? EmailTone.PROFESSIONAL];

    const candidate = await this.loadCandidate(organizationId, candidateId);

    let interview: Interview | null = null;
    if (dto.interviewId) {
      interview = await this.interviewsRepository.findOne({
        where: { id: dto.interviewId, organizationId, candidateId },
      });
      if (!interview) throw new NotFoundException('Interview not found for this candidate');
    }

    const system = `You are a helpful recruiting coordinator drafting an email to a job candidate, in a ${tone} tone. Respond with ONLY a JSON object (no markdown fences, no commentary) matching exactly this shape:
{ "subject": <string>, "body": <string, plain text or simple HTML paragraphs, no more than a few short paragraphs> }`;

    const prompt = `Email type: ${dto.type}
Candidate first name: ${candidate.name.split(' ')[0]}
Job title: ${candidate.job?.title ?? 'the role'}
${interview ? `Interview round: ${interview.roundName}\nScheduled at: ${interview.scheduledAt.toISOString()}\n` : ''}${dto.additionalContext ? `Recruiter's guidance: ${dto.additionalContext}\n` : ''}
Write a ${tone} "${dto.type}" email for this candidate.`;

    return this.llmService.completeJson<ComposedEmail>({ system, prompt }, () => ({
      subject: `[mock] ${dto.type} — ${candidate.job?.title ?? 'your application'}`,
      body: `<p>Hi ${candidate.name.split(' ')[0]},</p><p>[mock] This is a deterministic canned "${dto.type}" email body generated by LLM_PROVIDER=mock for local development/testing — not a real draft.</p>`,
    }));
  }

  async send(
    organizationId: string,
    candidateId: string,
    sentByUserId: string,
    dto: SendEmailDto,
  ): Promise<CandidateEmail> {
    const candidate = await this.loadCandidate(organizationId, candidateId);
    await this.mailAccountsService.sendCandidateEmail(sentByUserId, organizationId, {
      to: candidate.email,
      subject: dto.subject,
      html: dto.body,
    });

    const email = this.emailsRepository.create({
      organizationId,
      candidateId,
      type: dto.type,
      subject: dto.subject,
      body: dto.body,
      sentByUserId,
      sentAt: new Date(),
    });
    return this.emailsRepository.save(email);
  }

  async list(organizationId: string, candidateId: string): Promise<CandidateEmail[]> {
    await this.loadCandidate(organizationId, candidateId);
    return this.emailsRepository.find({
      where: { candidateId, organizationId },
      relations: { sentBy: true },
      order: { sentAt: 'DESC' },
    });
  }
}
